name: ${PROJECT_NAME}

services:
  db:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_VOLUME_NAME}:/var/lib/postgresql/data
